name: quizzler
description: "Quizzler - The Ultimate Knowledge Challenge"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  # Updated Firebase and Google Sign-In versions
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.0.2
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  get_storage: ^2.1.1
  share_plus: ^7.2.1
  url_launcher: ^6.2.2
  package_info_plus: ^4.2.0
  shared_preferences: ^2.2.2
  vibration: ^3.1.3
  just_audio: ^0.9.46
  http: ^1.2.1
  flutter_dotenv: ^5.1.0
  lottie: ^3.3.1
  google_generative_ai: ^0.4.7
  confetti: ^0.8.0
  curved_navigation_bar: ^1.0.6
  email_validator: ^3.0.0
  rename_app: ^1.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/image1.png
    - assets/google_logo.png
    - .env
    - assets/animation.json

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/Poppins/Poppins-Regular.ttf
        - asset: assets/Poppins/Poppins-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  image_path: "assets/app_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app_logo.png"
  min_sdk_android: 21

