#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/yashnandwani/Developer/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/yashnandwani/Developer/Flutter_Projects/Quiz-App/Quiz-App"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=/Users/yashnandwani/Developer/Flutter_Projects/Quiz-App/Quiz-App/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
export "FLUTTER_CLI_BUILD_MODE=debug"
export "DART_DEFINES=RkxVVFRFUl9WRVJTSU9OPTMuMzMuMC0xLjAucHJlLjU4Nw==,RkxVVFRFUl9DSEFOTkVMPW1hc3Rlcg==,RkxVVFRFUl9HSVRfVVJMPWh0dHA6Ly9naXRodWIuY29tL2ZsdXR0ZXIvZmx1dHRlci5naXQ=,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049NDRjNmUwNjVkNw==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049NDRjNmUwNjVkNw==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My45LjAgKGJ1aWxkIDMuOS4wLTI1MS4wLmRldik="
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/yashnandwani/Developer/Flutter_Projects/Quiz-App/Quiz-App/.dart_tool/package_config.json"
